In [2]:
import numpy as np
import torch
import torch
from torch.autograd import Variable
import numpy as np
import torch.functional as F
import torch.nn.functional as F
import os

In [3]:

import sys
import numpy as np
# add gensim source code fro this path
sys.path.insert(0, "../../../")
sys.path.insert(0, "../../gensim/")

# import modules & set up logging
import gensim, logging

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
                
                

## Import the training data from file

In [4]:
from smart_open import smart_open
class MySentences(object):
    def __init__(self, dirname):
        self.dirname = dirname
 
    def __iter__(self):
        for fname in os.listdir(self.dirname):
            for line in smart_open(os.path.join(self.dirname, fname), 'r'):
                yield line.split()

In [7]:
# point to sentences to be learned file here
my_sentences_fn = '../..//ULL/data/Practical2/wa/english_full/'
my_sentences_fn = '../..//ULL/data/Practical2/wa/english/'

sentences = MySentences(my_sentences_fn) # a memory-friendly iterator
print(list(sentences))

[['each', 'of', 'them', 'is', 'very', 'complex', ',', 'but', 'the', 'link', 'between', 'the', 'two', 'is', 'even', 'more', 'complex', 'which', 'makes', 'the', 'whole', 'situation', 'for', 'most', 'people', 'understandably', 'confusing', '.'], ['the', 'commissionners', 'went', 'on', ':'], ['they', 'are', 'constrained', 'by', 'limits', 'which', 'are', 'imposed', 'in', 'order', 'to', 'ensure', 'that', 'the', 'freedom', 'of', 'one', 'person', 'does', 'not', 'violate', 'that', 'of', 'another', '.'], ['it', 'made', 'the', 'buying', 'and', 'selling', 'of', 'sex', 'on', 'our', 'streets', 'legal', 'for', 'all', 'intents', 'and', 'purposes', '.'], ['the', 'way', 'in', 'which', 'Bill', 'C', '-', '49', 'has', 'been', 'presented', 'today', 'gives', 'us', 'the', 'feeling', 'that', 'only', 'the', 'prostitutes', 'are', 'punished', 'and', 'stigmatized', '.'], ['I', 'never', 'met', 'a', 'street', 'hooker', 'who', 'wanted', 'to', 'be', 'there', '.'], ['the', 'establishment', 'of', 'the', 'standing', 'com

In [8]:

# corpus = [
#     'he is a king',
#     'she is a queen',
#     'he is a man',
#     'she is a woman',
#     'warsaw is poland capital',
#     'berlin is germany capital',
#     'paris is france capital',
# ]


# def tokenize_corpus(corpus):
#     tokens = [x.split() for x in corpus]
#     return tokens

# tokenized_corpus = tokenize_corpus(corpus)


vocabulary = []
for sentence in sentences:
    for token in sentence:
        if token not in vocabulary:
            vocabulary.append(token)

word2idx = {w: idx for (idx, w) in enumerate(vocabulary)}
idx2word = {idx: w for (idx, w) in enumerate(vocabulary)}


vocabulary_size = len(vocabulary)

In [9]:
for i in vocabulary:
    if i == 'he':
        print(i)

In [10]:
window_size = 2
idx_pairs = []
# for each sentence
for sentence in sentences:
    indices = [word2idx[word] for word in sentence]
    # for each word, threated as center word
    for center_word_pos in range(len(indices)):
        # for each window position
        for w in range(-window_size, window_size + 1):
            context_word_pos = center_word_pos + w
            # make soure not jump out sentence
            if context_word_pos < 0 or context_word_pos >= len(indices) or center_word_pos == context_word_pos:
                continue
            context_word_idx = indices[context_word_pos]
            idx_pairs.append((indices[center_word_pos], context_word_idx))

idx_pairs = np.array(idx_pairs) # it will be useful to have this as numpy array



In [11]:

def get_input_layer(word_idx):
    x = torch.zeros(vocabulary_size).float()
    x[word_idx] = 1.0
    return x

In [12]:
print(np.shape(W2))

NameError: name 'W2' is not defined

In [13]:
import time
start_time = time.time()

end_time=time.time()
print("Took %.2f"%(end_time-start_time))

Took 0.00


In [14]:
import time
start_time = time.time()

embedding_dims = 5
# D: Latent variables / embed dimensions
# V: vocabulary size
# W1: shape(VxD)
W1 = Variable(torch.randn(embedding_dims, vocabulary_size).float(), requires_grad=True)
W2 = Variable(torch.randn(vocabulary_size, embedding_dims).float(), requires_grad=True)
num_epochs = 101
learning_rate = 0.001


for epo in range(num_epochs):
    loss_val = 0
    # Compute loss for each training pair after predicting it with the NN
    for data, target in idx_pairs:
        # input layer: hot vectors?
        x = Variable(get_input_layer(data)).float()
        #print(data,target,  x)
        y_true = Variable(torch.from_numpy(np.array([target])).long())
        
        # this selects the embedding corresponding to x hot vector
        # z1: size(1xZ) column vec
        z1 = torch.matmul(W1, x)
        
        # multiply selected embedding, z1 with contexts matrix
        # computes the actual response z2 = yhat
        z2 = torch.matmul(W2, z1)
        
        # pass z2 through softmax to get probabilities
        # and compute log
        log_softmax = F.log_softmax(z2, dim=0)
        
        # ERROR: subtract model predictions from true contexts
        # print(log_softmax.view(1,-1))
        loss = F.nll_loss(log_softmax.view(1,-1), y_true)
        #print("loss",loss.data[0])
        loss_val += loss.data[0]
        # Run backprop - backprogate error 
        loss.backward()
        # Compute gradient of the parameters matrix W1, evaluate at data
        
        W1.data -= learning_rate * W1.grad.data
        W2.data -= learning_rate * W2.grad.data

        W1.grad.data.zero_()
        W2.grad.data.zero_()
    if epo % 10 == 0:    
        print('Loss at epo %s: %s/%s'%(epo, loss_val, len(idx_pairs)))
        

end_time=time.time()
print("Took %.2f"%(end_time-start_time))

/Users/efiathieniti/miniconda3/envs/py35/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


Loss at epo 0: tensor(19535.4629)/2422
Loss at epo 10: tensor(17245.0137)/2422
Loss at epo 20: tensor(16259.0898)/2422
Loss at epo 30: tensor(15661.2754)/2422
Loss at epo 40: tensor(15238.1240)/2422
Loss at epo 50: tensor(14910.4189)/2422
Loss at epo 60: tensor(14641.3564)/2422
Loss at epo 70: tensor(14411.1230)/2422
Loss at epo 80: tensor(14208.2285)/2422
Loss at epo 90: tensor(14025.7725)/2422
Loss at epo 100: tensor(13859.3662)/2422
Took 46.61


In [15]:
print(vocabulary_size)
# Embeddings are the W1

print(vocabulary[1])

322
of


In [16]:
W1.detach().numpy()[:,1]

array([ 0.1363363 ,  0.39781931,  0.25489193, -0.38880429,  0.54477477], dtype=float32)

## Save the embeddings learned as gensim model

In [17]:
import csv
embeddings_file='embeddings_simple.txt'
with open(embeddings_file, 'w') as csvfile:
    writer = csv.writer(csvfile, delimiter = ' ')
    writer.writerow([vocabulary_size, embedding_dims])
    for i in range(vocabulary_size):    
        line= [vocabulary[i]] + list(W1.detach().numpy()[:,i])
        writer.writerow(line)
    

In [48]:
embeddings_file='embeddings_simple.txt'
embeddings_file='embeddings_new.txt'


## Load the embeddings learned 

In [49]:

from gensim.models import KeyedVectors
#word_vectors = KeyedVectors.load_word2vec_format('../../../ULL/data/bow2.words.bz2', binary=False)  # C text format
word_vectors = KeyedVectors.load_word2vec_format(embeddings_file, binary=False)  # C binary format

2018-05-02 16:39:33,402 : INFO : loading projection weights from embeddings_new.txt
2018-05-02 16:39:33,429 : INFO : loaded (1732, 5) matrix from embeddings_new.txt


In [20]:
for i in vocabulary:
    print(i)

each
of
them
is
very
complex
,
but
the
link
between
two
even
more
which
makes
whole
situation
for
most
people
understandably
confusing
.
commissionners
went
on
:
they
are
constrained
by
limits
imposed
in
order
to
ensure
that
freedom
one
person
does
not
violate
another
it
made
buying
and
selling
sex
our
streets
legal
all
intents
purposes
way
Bill
C
-
49
has
been
presented
today
gives
us
feeling
only
prostitutes
punished
stigmatized
I
never
met
a
street
hooker
who
wanted
be
there
establishment
standing
committee
unanimous
consent
House
June
28
1985
already
noted
have
stressed
CDC
as
an
example
creative
aggressive
effective
public
ownership
so
far
around
$
250,000
issued
institute
grants
research
or
education
activity
let
me
conclude
think
we
should
take
hard
look
at
this
justification
determine
whether
cost
interest
however
raises
some
pertinent
questions
given
cut
backs
announced
Budget
last
spring
see
licence
fee
going
up
from
25
500
would
easy
say
these
sanctions
followed
rather
than


In [50]:
print(word_vectors.similarity('disturbed', 'pervasive'))


0.64288


In [51]:
word_vectors.most_similar(positive=['woman', 'king'], negative=['man'])
[('queen', 0.50882536), ...]

word_vectors.most_similar_cosmul(positive=['woman', 'king'], negative=['man'])
[('queen', 0.71382287), ...]

word_vectors.doesnt_match("breakfast cereal dinner lunch".split())
'cereal'



2018-05-02 16:39:46,292 : INFO : precomputing L2-norms of word weight vectors


KeyError: "word 'woman' not in vocabulary"

In [52]:
word_vectors.doesnt_match("breakfast cereal dinner lunch".split())
'cereal'


2018-05-02 16:39:48,912 : WARNING : vectors for words {'dinner', 'cereal', 'lunch', 'breakfast'} are not present in the model, ignoring these words


ValueError: cannot select a word from an empty list

In [53]:
word_vectors.similarity('woman', 'man')


KeyError: "word 'woman' not in vocabulary"

Evaluate model, similarity, analogy

# Bayesian skip-gram

1. 
For each word/training point (xi) calculate elbo (loss)
xi - training points


In [46]:


# elbo: 
# calculate mu_xi and sigma_xi (length: V)
# log(z | mu_xi, sigma_xi)


import time
start_time = time.time()

embedding_dims = 5
# D: Latent variables / embed dimensions
# V: vocabulary size
# W1: shape(VxD)
W1 = Variable(torch.randn(embedding_dims, vocabulary_size).float(), requires_grad=True)
W2 = Variable(torch.randn(vocabulary_size, embedding_dims).float(), requires_grad=True)
num_epochs = 5
learning_rate = 0.001


for epo in range(num_epochs):
    print("epo ",epo)
    loss_val = 0
    # Compute loss for each training pair after predicting it with the NN
    for data, target in idx_pairs:
        print("data",data)
        # input layer: hot vectors?
        x_d = Variable(get_input_layer(data)).float()
        x_t = Variable(get_input_layer(target)).float()

        # this selects the embedding corresponding to x hot vector
        # z1: size(1xZ) column vec
        z_d = torch.matmul(W1, x_d)
        z_t = torch.matmul(W1, x_t)
        z = torch.cat((z_d, z_t), 0)
        #print(z)
        # Encoder
        z = F.relu(z)
        
        # During inference, we simply spit out the mean of the

        std = logvar.mul(0.5).exp_()  # type: Variable
        mu, logvar = self.encode(x.view(-1, 784))
        eps = Variable(std.data.new(std.size()).normal_())

        
        
        log_softmax = F.log_softmax(z2, dim=0)

        

epo  0
data 0
tensor([ 0.4625,  0.3210,  0.0000,  0.0000,  0.4706,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 0
tensor([ 0.4625,  0.3210,  0.0000,  0.0000,  0.4706,  0.0000,  0.6466,
         0.0000,  0.0000,  0.0701])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.4625,  0.3210,
         0.0000,  0.0000,  0.4706])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  0.6466,
         0.0000,  0.0000,  0.0701])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  0.7732,
         1.4456,  0.0000,  0.5693])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  0.4625,  0.3210,
         0.0000,  0.0000,  0.4706])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  0.0000,  0.7732,
         1.4456,  0.0000,  0.5693])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  0.9038,  0.0000,
   

tensor([ 0.4853,  0.1077,  0.0766,  0.6611,  0.0000,  0.5246,  0.0000,
         0.0000,  0.0000,  0.8124])
data 64
tensor([ 0.4853,  0.1077,  0.0766,  0.6611,  0.0000,  0.3498,  0.0000,
         0.0000,  0.5190,  0.0539])
data 64
tensor([ 0.4853,  0.1077,  0.0766,  0.6611,  0.0000,  0.6653,  0.0862,
         0.3067,  0.0000,  0.0000])
data 64
tensor([ 0.4853,  0.1077,  0.0766,  0.6611,  0.0000,  0.0080,  0.0000,
         0.2101,  0.0000,  0.0000])
data 65
tensor([ 0.6653,  0.0862,  0.3067,  0.0000,  0.0000,  0.3498,  0.0000,
         0.0000,  0.5190,  0.0539])
data 65
tensor([ 0.6653,  0.0862,  0.3067,  0.0000,  0.0000,  0.4853,  0.1077,
         0.0766,  0.6611,  0.0000])
data 65
tensor([ 0.6653,  0.0862,  0.3067,  0.0000,  0.0000,  0.0080,  0.0000,
         0.2101,  0.0000,  0.0000])
data 65
tensor([ 0.6653,  0.0862,  0.3067,  0.0000,  0.0000,  0.0494,  0.1900,
         0.0000,  0.0000,  0.0000])
data 66
tensor([ 0.0080,  0.0000,  0.2101,  0.0000,  0.0000,  0.4853,  0.1077,
         

tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0000,  0.0000,
         1.7145,  0.0000,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.6260,  0.5747,
         1.6286,  0.0000,  2.7496])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.8327,  0.0000,
         0.0397,  0.5506,  1.0354])
data 112
tensor([ 0.6260,  0.5747,  1.6286,  0.0000,  2.7496,  0.0000,  0.0000,
         1.7145,  0.0000,  0.0000])
data 112
tensor([ 0.6260,  0.5747,  1.6286,  0.0000,  2.7496,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 112
tensor([ 0.6260,  0.5747,  1.6286,  0.0000,  2.7496,  0.8327,  0.0000,
         0.0397,  0.5506,  1.0354])
data 112
tensor([ 0.6260,  0.5747,  1.6286,  0.0000,  2.7496,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0200])
data 34
tensor([ 0.8327,  0.0000,  0.0397,  0.5506,  1.0354,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 34
tensor([ 0.8327,  0.0000,  0.0397,  0.5506,  1.0354,  0.6260,  0.5747,
       

tensor([ 0.6217,  0.9256,  0.4274,  0.8396,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 159
tensor([ 0.6217,  0.9256,  0.4274,  0.8396,  0.0000,  0.2162,  0.0000,
         0.7949,  0.0000,  0.4726])
data 159
tensor([ 0.6217,  0.9256,  0.4274,  0.8396,  0.0000,  0.2832,  0.0000,
         0.7465,  1.1789,  0.3843])
data 160
tensor([ 0.2162,  0.0000,  0.7949,  0.0000,  0.4726,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 160
tensor([ 0.2162,  0.0000,  0.7949,  0.0000,  0.4726,  0.6217,  0.9256,
         0.4274,  0.8396,  0.0000])
data 160
tensor([ 0.2162,  0.0000,  0.7949,  0.0000,  0.4726,  0.2832,  0.0000,
         0.7465,  1.1789,  0.3843])
data 160
tensor([ 0.2162,  0.0000,  0.7949,  0.0000,  0.4726,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 161
tensor([ 0.2832,  0.0000,  0.7465,  1.1789,  0.3843,  0.6217,  0.9256,
         0.4274,  0.8396,  0.0000])
data 161
tensor([ 0.2832,  0.0000,  0.7465,  1.1789,  0.3843,  0.2162,  0.0000,
 

tensor([ 0.2792,  1.3562,  0.0000,  0.2705,  0.0995,  0.3596,  2.2117,
         0.0000,  0.8276,  0.0000])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  0.8176,  0.0000,
         0.4990,  0.5230,  0.0000])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  0.2792,  1.3562,
         0.0000,  0.2705,  0.0995])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  0.3596,  2.2117,
         0.0000,  0.8276,  0.0000])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  0.1080,  0.8744,
         0.0000,  0.2145,  0.0000])
data 192
tensor([ 0.3596,  2.2117,  0.0000,  0.8276,  0.0000,  0.2792,  1.3562,
         0.0000,  0.2705,  0.0995])
data 192
tensor([ 0.3596,  2.2117,  0.0000,  0.8276,  0.0000,  0.0000,  0.5715,
         0.0000,  1.5224,  0.0000])
data 192
tensor([ 0.3596,  2.2117,  0.0000,  0.8276,  0.0000,  0.1080,  0.8744,
         0.0000,  0.2145,  0.0000])
data 192
tensor([ 0.3596,  2.2117,  0.0000,  0.8276,  0.0000,  0.0000,  0.2029,
     

data 226
tensor([ 1.3231,  0.7665,  0.6620,  3.1234,  1.3746,  1.5312,  0.8795,
         2.1102,  1.9857,  0.0000])
data 226
tensor([ 1.3231,  0.7665,  0.6620,  3.1234,  1.3746,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 18
tensor([ 1.5312,  0.8795,  2.1102,  1.9857,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 18
tensor([ 1.5312,  0.8795,  2.1102,  1.9857,  0.0000,  1.3231,  0.7665,
         0.6620,  3.1234,  1.3746])
data 18
tensor([ 1.5312,  0.8795,  2.1102,  1.9857,  0.0000,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 18
tensor([ 1.5312,  0.8795,  2.1102,  1.9857,  0.0000,  0.0000,  0.5844,
         0.0000,  0.9213,  0.2290])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  1.3231,  0.7665,
         0.6620,  3.1234,  1.3746])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  1.5312,  0.8795,
         2.1102,  1.9857,  0.0000])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  0.0000,  0.5844,

tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  1.5504,
         1.8270,  0.0000,  0.0372])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  0.0000,
         0.0000,  0.0000,  1.5607])
data 266
tensor([ 0.0000,  1.5504,  1.8270,  0.0000,  0.0372,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 266
tensor([ 0.0000,  1.5504,  1.8270,  0.0000,  0.0372,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 266
tensor([ 0.0000,  1.5504,  1.8270,  0.0000,  0.0372,  0.0000,  0.0000,
         0.0000,  0.0000,  1.5607])
data 266
tensor([ 0.0000,  1.5504,  1.8270,  0.0000,  0.0372,  0.4677,  0.0000,
         0.0538,  2.3792,  0.1168])
data 38
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.5607,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 38
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.5607,  0.0000,  1.5504,
       

tensor([ 0.0000,  0.4985,  0.0000,  0.0000,  1.0364,  0.0000,  0.4570,
         0.0000,  0.0000,  0.0000])
data 297
tensor([ 0.0000,  0.4985,  0.0000,  0.0000,  1.0364,  0.1400,  0.0000,
         0.7864,  0.0000,  0.0000])
data 298
tensor([ 0.0000,  0.4570,  0.0000,  0.0000,  0.0000,  0.0000,  0.2726,
         0.5468,  0.0000,  0.0000])
data 298
tensor([ 0.0000,  0.4570,  0.0000,  0.0000,  0.0000,  0.0000,  0.4985,
         0.0000,  0.0000,  1.0364])
data 298
tensor([ 0.0000,  0.4570,  0.0000,  0.0000,  0.0000,  0.1400,  0.0000,
         0.7864,  0.0000,  0.0000])
data 298
tensor([ 0.0000,  0.4570,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 299
tensor([ 0.1400,  0.0000,  0.7864,  0.0000,  0.0000,  0.0000,  0.4985,
         0.0000,  0.0000,  1.0364])
data 299
tensor([ 0.1400,  0.0000,  0.7864,  0.0000,  0.0000,  0.0000,  0.4570,
         0.0000,  0.0000,  0.0000])
data 299
tensor([ 0.1400,  0.0000,  0.7864,  0.0000,  0.0000,  0.0000,  0.0000,
 

data 31
tensor([ 0.0000,  0.0000,  1.7145,  0.0000,  0.0000,  0.0000,  1.0022,
         0.0000,  0.5614,  0.0000])
data 31
tensor([ 0.0000,  0.0000,  1.7145,  0.0000,  0.0000,  0.0000,  0.0000,
         0.2212,  0.4445,  0.1213])
data 32
tensor([ 0.0000,  1.0022,  0.0000,  0.5614,  0.0000,  0.0000,  0.5037,
         0.0000,  0.0000,  0.0000])
data 32
tensor([ 0.0000,  1.0022,  0.0000,  0.5614,  0.0000,  0.0000,  0.0000,
         1.7145,  0.0000,  0.0000])
data 32
tensor([ 0.0000,  1.0022,  0.0000,  0.5614,  0.0000,  0.0000,  0.0000,
         0.2212,  0.4445,  0.1213])
data 32
tensor([ 0.0000,  1.0022,  0.0000,  0.5614,  0.0000,  0.0000,  0.4769,
         0.0000,  0.0000,  0.0000])
data 14
tensor([ 0.0000,  0.0000,  0.2212,  0.4445,  0.1213,  0.0000,  0.0000,
         1.7145,  0.0000,  0.0000])
data 14
tensor([ 0.0000,  0.0000,  0.2212,  0.4445,  0.1213,  0.0000,  1.0022,
         0.0000,  0.5614,  0.0000])
data 14
tensor([ 0.0000,  0.0000,  0.2212,  0.4445,  0.1213,  0.0000,  0.4769,
 

         0.0453,  0.0000,  0.0000])
data 88
tensor([ 1.0411,  0.0000,  0.5855,  0.3867,  1.2448,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 88
tensor([ 1.0411,  0.0000,  0.5855,  0.3867,  1.2448,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  1.2011,
         0.0453,  0.0000,  0.0000])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  1.0411,  0.0000,
         0.5855,  0.3867,  1.2448])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.8973,  0.0000,
         0.0000,  0.0000,  0.0323])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  1.0411,  0.0000,
         0.5855,  0.3867,  1.2448])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,

data 137
tensor([ 0.0000,  0.6598,  2.2960,  0.1768,  0.0000,  0.4287,  0.0000,
         0.0000,  0.0000,  2.0789])
data 137
tensor([ 0.0000,  0.6598,  2.2960,  0.1768,  0.0000,  0.9038,  0.0000,
         0.0000,  0.0000,  0.0000])
data 137
tensor([ 0.0000,  0.6598,  2.2960,  0.1768,  0.0000,  0.2458,  0.3824,
         0.3940,  2.4814,  0.1805])
data 137
tensor([ 0.0000,  0.6598,  2.2960,  0.1768,  0.0000,  1.2244,  0.0000,
         0.0000,  1.8640,  0.0076])
data 138
tensor([ 0.2458,  0.3824,  0.3940,  2.4814,  0.1805,  0.9038,  0.0000,
         0.0000,  0.0000,  0.0000])
data 138
tensor([ 0.2458,  0.3824,  0.3940,  2.4814,  0.1805,  0.0000,  0.6598,
         2.2960,  0.1768,  0.0000])
data 138
tensor([ 0.2458,  0.3824,  0.3940,  2.4814,  0.1805,  1.2244,  0.0000,
         0.0000,  1.8640,  0.0076])
data 138
tensor([ 0.2458,  0.3824,  0.3940,  2.4814,  0.1805,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 139
tensor([ 1.2244,  0.0000,  0.0000,  1.8640,  0.0076,  0.0000,  

         1.2497,  0.8808,  0.0741])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  1.5312,  0.8795,
         2.1102,  1.9857,  0.0000])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  1.6348,  0.0000,
         0.0000,  2.3143,  1.3737])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  0.0000,  0.5402,
         0.0000,  0.0000,  0.8726])
data 183
tensor([ 1.6348,  0.0000,  0.0000,  2.3143,  1.3737,  1.5312,  0.8795,
         2.1102,  1.9857,  0.0000])
data 183
tensor([ 1.6348,  0.0000,  0.0000,  2.3143,  1.3737,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 183
tensor([ 1.6348,  0.0000,  0.0000,  2.3143,  1.3737,  0.0000,  0.5402,
         0.0000,  0.0000,  0.8726])
data 183
tensor([ 1.6348,  0.0000,  0.0000,  2.3143,  1.3737,  0.7507,  0.6401,
         0.0000,  0.0000,  1.6847])
data 184
tensor([ 0.0000,  0.5402,  0.0000,  0.0000,  0.8726,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 184
tensor([ 0.0000,  0.5402,  0.0

tensor([ 0.0000,  0.9997,  0.4302,  0.6926,  0.3512,  0.3634,  0.0000,
         1.3940,  0.0000,  0.0000])
data 216
tensor([ 0.0000,  0.9997,  0.4302,  0.6926,  0.3512,  0.0000,  1.8276,
         0.0000,  0.6419,  0.0000])
data 216
tensor([ 0.0000,  0.9997,  0.4302,  0.6926,  0.3512,  0.2883,  0.4474,
         1.8577,  0.0000,  0.7733])
data 216
tensor([ 0.0000,  0.9997,  0.4302,  0.6926,  0.3512,  0.1080,  0.8744,
         0.0000,  0.2145,  0.0000])
data 217
tensor([ 0.2883,  0.4474,  1.8577,  0.0000,  0.7733,  0.0000,  1.8276,
         0.0000,  0.6419,  0.0000])
data 217
tensor([ 0.2883,  0.4474,  1.8577,  0.0000,  0.7733,  0.0000,  0.9997,
         0.4302,  0.6926,  0.3512])
data 217
tensor([ 0.2883,  0.4474,  1.8577,  0.0000,  0.7733,  0.1080,  0.8744,
         0.0000,  0.2145,  0.0000])
data 217
tensor([ 0.2883,  0.4474,  1.8577,  0.0000,  0.7733,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 36
tensor([ 0.1080,  0.8744,  0.0000,  0.2145,  0.0000,  0.0000,  0.9997,
  

         0.1489,  0.0000,  0.0000])
data 193
tensor([ 0.0000,  0.0662,  0.9826,  0.0000,  0.0000,  1.4322,  1.1425,
         0.0000,  0.0000,  0.0000])
data 193
tensor([ 0.0000,  0.0662,  0.9826,  0.0000,  0.0000,  1.1517,  0.0000,
         0.8544,  1.3958,  0.0000])
data 193
tensor([ 0.0000,  0.0662,  0.9826,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 253
tensor([ 1.1517,  0.0000,  0.8544,  1.3958,  0.0000,  1.4322,  1.1425,
         0.0000,  0.0000,  0.0000])
data 253
tensor([ 1.1517,  0.0000,  0.8544,  1.3958,  0.0000,  0.0000,  0.0662,
         0.9826,  0.0000,  0.0000])
data 253
tensor([ 1.1517,  0.0000,  0.8544,  1.3958,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 253
tensor([ 1.1517,  0.0000,  0.8544,  1.3958,  0.0000,  2.0390,  0.0182,
         1.3158,  0.0952,  0.1921])
data 254
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0662,
         0.9826,  0.0000,  0.0000])
data 254
tensor([ 0.0000,  0.0000,  

tensor([ 0.0000,  0.7732,  1.4456,  0.0000,  0.5693,  0.0000,  0.0000,
         0.0000,  0.4723,  0.0000])
data 3
tensor([ 0.0000,  0.7732,  1.4456,  0.0000,  0.5693,  0.9038,  0.0000,
         0.0000,  0.0000,  0.0000])
data 3
tensor([ 0.0000,  0.7732,  1.4456,  0.0000,  0.5693,  0.2671,  0.0000,
         0.0000,  0.0000,  0.3320])
data 4
tensor([ 0.9038,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.4723,  0.0000])
data 4
tensor([ 0.9038,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.7732,
         1.4456,  0.0000,  0.5693])
data 4
tensor([ 0.9038,  0.0000,  0.0000,  0.0000,  0.0000,  0.2671,  0.0000,
         0.0000,  0.0000,  0.3320])
data 4
tensor([ 0.9038,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  1.5607])
data 289
tensor([ 0.2671,  0.0000,  0.0000,  0.0000,  0.3320,  0.0000,  0.7732,
         1.4456,  0.0000,  0.5693])
data 289
tensor([ 0.2671,  0.0000,  0.0000,  0.0000,  0.3320,  0.9038,  0.0000,
         0.00

data 0
tensor([ 0.4625,  0.3210,  0.0000,  0.0000,  0.4706,  0.0000,  0.6466,
         0.0000,  0.0000,  0.0701])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.4625,  0.3210,
         0.0000,  0.0000,  0.4706])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  0.6466,
         0.0000,  0.0000,  0.0701])
data 1
tensor([ 1.4971,  0.0000,  0.7202,  0.0000,  0.6288,  0.0000,  0.7732,
         1.4456,  0.0000,  0.5693])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  0.4625,  0.3210,
         0.0000,  0.0000,  0.4706])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  0.0000,  0.7732,
         1.4456,  0.0000,  0.5693])
data 2
tensor([ 0.0000,  0.6466,  0.0000,  0.0000,  0.0701,  0.9038,  0.0000,
         0.0000,  0.0000,  0.0000])
data 3
tensor([ 0.0000,  0.7732,  1.4456,  0.0000,  0.5693,  1.4971,  0.0000,
         0

tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0494,  0.1900,
         0.0000,  0.0000,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0000,  0.0000,
         0.9689,  1.0342,  1.2235])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.3171,  0.0000,
         0.8472,  0.6028,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  1.5607])
data 69
tensor([ 0.3171,  0.0000,  0.8472,  0.6028,  0.0000,  0.0000,  0.0000,
         0.9689,  1.0342,  1.2235])
data 69
tensor([ 0.3171,  0.0000,  0.8472,  0.6028,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 69
tensor([ 0.3171,  0.0000,  0.8472,  0.6028,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  1.5607])
data 69
tensor([ 0.3171,  0.0000,  0.8472,  0.6028,  0.0000,  0.2175,  0.0962,
         0.0000,  1.1981,  1.6472])
data 38
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.5607,  0.0000,  0.1369,
         0.8

tensor([ 0.0000,  0.3053,  0.0000,  0.5918,  0.0000,  0.0000,  0.1513,
         0.0000,  1.7269,  0.0000])
data 123
tensor([ 0.0000,  0.3053,  0.0000,  0.5918,  0.0000,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 124
tensor([ 0.0000,  0.1513,  0.0000,  1.7269,  0.0000,  0.0000,  0.8774,
         0.0000,  0.2483,  0.0000])
data 124
tensor([ 0.0000,  0.1513,  0.0000,  1.7269,  0.0000,  0.0000,  0.3053,
         0.0000,  0.5918,  0.0000])
data 124
tensor([ 0.0000,  0.1513,  0.0000,  1.7269,  0.0000,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 124
tensor([ 0.0000,  0.1513,  0.0000,  1.7269,  0.0000,  0.2716,  0.0909,
         0.0000,  0.0000,  0.9835])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  0.0000,  0.3053,
         0.0000,  0.5918,  0.0000])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  0.0000,  0.1513,
         0.0000,  1.7269,  0.0000])
data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  0.2716,  0.0909,
    

tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  1.5312,  0.8795,
         2.1102,  1.9857,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  0.3635,  0.0000,
         1.5981,  0.0000,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  0.0000,  1.8276,
         0.0000,  0.6419,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  0.0732,  1.0410,
         0.0000,  0.0000,  0.0000])
data 52
tensor([ 0.0000,  1.8276,  0.0000,  0.6419,  0.0000,  0.3635,  0.0000,
         1.5981,  0.0000,  0.0000])
data 52
tensor([ 0.0000,  1.8276,  0.0000,  0.6419,  0.0000,  0.0000,  0.9860,
         0.0000,  0.7566,  0.8767])
data 52
tensor([ 0.0000,  1.8276,  0.0000,  0.6419,  0.0000,  0.0732,  1.0410,
         0.0000,  0.0000,  0.0000])
data 52
tensor([ 0.0000,  1.8276,  0.0000,  0.6419,  0.0000,  1.3777,  0.0084,
         0.0000,  1.0028,  0.3983])
data 169
tensor([ 0.0732,  1.0410,  0.0000,  0.0000,  0.0000,  0.0000,  0.9860,
     

tensor([ 0.3148,  0.0000,  1.6240,  0.6385,  1.1458,  0.0000,  1.0955,
         0.0000,  0.0893,  0.0000])
data 42
tensor([ 0.3148,  0.0000,  1.6240,  0.6385,  1.1458,  0.0000,  0.0000,
         0.0000,  0.4723,  0.0000])
data 42
tensor([ 0.3148,  0.0000,  1.6240,  0.6385,  1.1458,  0.0000,  0.5715,
         0.0000,  1.5224,  0.0000])
data 42
tensor([ 0.3148,  0.0000,  1.6240,  0.6385,  1.1458,  0.2792,  1.3562,
         0.0000,  0.2705,  0.0995])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  0.0000,  0.0000,
         0.0000,  0.4723,  0.0000])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  0.3148,  0.0000,
         1.6240,  0.6385,  1.1458])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  0.2792,  1.3562,
         0.0000,  0.2705,  0.0995])
data 43
tensor([ 0.0000,  0.5715,  0.0000,  1.5224,  0.0000,  1.2886,  0.5414,
         0.0000,  0.0000,  1.0025])
data 173
tensor([ 0.2792,  1.3562,  0.0000,  0.2705,  0.0995,  0.3148,  0.0000,
        

data 77
tensor([ 0.0000,  0.0000,  1.1793,  0.0000,  0.0000,  0.0000,  0.0000,
         2.7306,  0.0000,  0.0000])
data 233
tensor([ 0.6056,  0.0000,  0.5598,  0.0000,  0.0000,  0.3162,  1.3044,
         0.0000,  1.4172,  0.0000])
data 233
tensor([ 0.6056,  0.0000,  0.5598,  0.0000,  0.0000,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 233
tensor([ 0.6056,  0.0000,  0.5598,  0.0000,  0.0000,  0.0000,  0.0000,
         2.7306,  0.0000,  0.0000])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.6056,  0.0000,
         0.5598,  0.0000,  0.0000])
data 234
tensor([ 0.4184,  0.4103,  1.5513,  0.1040,  1.0711,  1.4322,  1.1425,
         0.0000,  0.0000,  0.0000])
data 234
tensor([ 0.4184,  0.4103,  1.5513,  0.1040,  1.0711,  0.0000,  0.2323,
         0.0000,  1.1505,  0.0000])
data 28
tensor([ 1.4322,  1.1425,  0.0000,  0.0000,  0.0000,  0.4184,  0.41

tensor([ 0.3539,  0.0000,  0.4704,  1.4061,  1.2172,  0.3498,  0.0000,
         0.0000,  0.5190,  0.0539])
data 275
tensor([ 0.3549,  0.6111,  0.0000,  0.5871,  0.2000,  0.3539,  0.0000,
         0.4704,  1.4061,  1.2172])
data 275
tensor([ 0.3549,  0.6111,  0.0000,  0.5871,  0.2000,  0.3498,  0.0000,
         0.0000,  0.5190,  0.0539])
data 275
tensor([ 0.3549,  0.6111,  0.0000,  0.5871,  0.2000,  0.4853,  0.1077,
         0.0766,  0.6611,  0.0000])
data 63
tensor([ 0.3498,  0.0000,  0.0000,  0.5190,  0.0539,  0.3539,  0.0000,
         0.4704,  1.4061,  1.2172])
data 63
tensor([ 0.3498,  0.0000,  0.0000,  0.5190,  0.0539,  0.3549,  0.6111,
         0.0000,  0.5871,  0.2000])
data 63
tensor([ 0.3498,  0.0000,  0.0000,  0.5190,  0.0539,  0.4853,  0.1077,
         0.0766,  0.6611,  0.0000])
data 63
tensor([ 0.3498,  0.0000,  0.0000,  0.5190,  0.0539,  0.0000,  0.0000,
         0.4321,  0.0000,  0.0041])
data 64
tensor([ 0.4853,  0.1077,  0.0766,  0.6611,  0.0000,  0.3549,  0.6111,
      

data 304
tensor([ 0.8635,  0.0000,  0.0000,  1.9713,  0.0000,  0.0000,  0.6654,
         0.4551,  0.0000,  0.0000])
data 304
tensor([ 0.8635,  0.0000,  0.0000,  1.9713,  0.0000,  0.1315,  0.0000,
         0.0000,  1.8782,  0.0000])
data 305
tensor([ 0.0000,  0.6654,  0.4551,  0.0000,  0.0000,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 305
tensor([ 0.0000,  0.6654,  0.4551,  0.0000,  0.0000,  0.8635,  0.0000,
         0.0000,  1.9713,  0.0000])
data 305
tensor([ 0.0000,  0.6654,  0.4551,  0.0000,  0.0000,  0.1315,  0.0000,
         0.0000,  1.8782,  0.0000])
data 305
tensor([ 0.0000,  0.6654,  0.4551,  0.0000,  0.0000,  0.3849,  0.5058,
         0.8327,  0.4851,  0.0000])
data 306
tensor([ 0.1315,  0.0000,  0.0000,  1.8782,  0.0000,  0.8635,  0.0000,
         0.0000,  1.9713,  0.0000])
data 306
tensor([ 0.1315,  0.0000,  0.0000,  1.8782,  0.0000,  0.0000,  0.6654,
         0.4551,  0.0000,  0.0000])
data 306
tensor([ 0.1315,  0.0000,  0.0000,  1.8782,  0.0000,  0.3849,  

tensor([ 1.2886,  0.5414,  0.0000,  0.0000,  1.0025,  0.0000,  0.1547,
         0.0262,  0.0000,  0.0000])
data 40
tensor([ 1.2886,  0.5414,  0.0000,  0.0000,  1.0025,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 40
tensor([ 1.2886,  0.5414,  0.0000,  0.0000,  1.0025,  1.6255,  0.0000,
         0.0000,  0.9350,  1.4814])
data 40
tensor([ 1.2886,  0.5414,  0.0000,  0.0000,  1.0025,  0.3148,  0.0000,
         1.6240,  0.6385,  1.1458])
data 41
tensor([ 1.6255,  0.0000,  0.0000,  0.9350,  1.4814,  1.4971,  0.0000,
         0.7202,  0.0000,  0.6288])
data 41
tensor([ 1.6255,  0.0000,  0.0000,  0.9350,  1.4814,  1.2886,  0.5414,
         0.0000,  0.0000,  1.0025])
data 41
tensor([ 1.6255,  0.0000,  0.0000,  0.9350,  1.4814,  0.3148,  0.0000,
         1.6240,  0.6385,  1.1458])
data 41
tensor([ 1.6255,  0.0000,  0.0000,  0.9350,  1.4814,  0.0000,  0.5715,
         0.0000,  1.5224,  0.0000])
data 42
tensor([ 0.3148,  0.0000,  1.6240,  0.6385,  1.1458,  1.2886,  0.5414,
         

tensor([ 0.5350,  0.0000,  1.2496,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 95
tensor([ 0.5350,  0.0000,  1.2496,  0.0000,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 96
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  1.2138,  1.6951])
data 96
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.5350,  0.0000,
         1.2496,  0.0000,  0.0000])
data 96
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 96
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.9617,  0.0000,
         0.0000,  0.0000,  1.9505])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.5350,  0.0000,
         1.2496,  0.0000,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.9617,  0.0000,
         0.0

tensor([ 0.0000,  1.0516,  0.0000,  0.0000,  0.8110,  0.9541,  0.2173,
         0.0000,  0.0000,  0.0000])
data 149
tensor([ 1.7625,  0.3058,  0.7387,  0.0000,  1.3867,  0.0000,  0.0000,
         1.3578,  0.2504,  0.0000])
data 149
tensor([ 1.7625,  0.3058,  0.7387,  0.0000,  1.3867,  0.0000,  1.0516,
         0.0000,  0.0000,  0.8110])
data 149
tensor([ 1.7625,  0.3058,  0.7387,  0.0000,  1.3867,  0.9541,  0.2173,
         0.0000,  0.0000,  0.0000])
data 149
tensor([ 1.7625,  0.3058,  0.7387,  0.0000,  1.3867,  0.0700,  1.0616,
         0.3319,  0.0000,  0.0000])
data 150
tensor([ 0.9541,  0.2173,  0.0000,  0.0000,  0.0000,  0.0000,  1.0516,
         0.0000,  0.0000,  0.8110])
data 150
tensor([ 0.9541,  0.2173,  0.0000,  0.0000,  0.0000,  1.7625,  0.3058,
         0.7387,  0.0000,  1.3867])
data 150
tensor([ 0.9541,  0.2173,  0.0000,  0.0000,  0.0000,  0.0700,  1.0616,
         0.3319,  0.0000,  0.0000])
data 150
tensor([ 0.9541,  0.2173,  0.0000,  0.0000,  0.0000,  0.7507,  0.6401,
 

tensor([ 0.0000,  0.0000,  0.0685,  0.4387,  2.0268,  0.0000,  0.8774,
         0.0000,  0.2483,  0.0000])
data 38
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.5607,  0.0000,  0.0000,
         0.0000,  0.4723,  0.0000])
data 38
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.5607,  0.0000,  0.0000,
         0.0685,  0.4387,  2.0268])
data 38
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.5607,  0.0000,  0.8774,
         0.0000,  0.2483,  0.0000])
data 38
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.5607,  0.5350,  0.0000,
         1.2496,  0.0000,  0.0000])
data 122
tensor([ 0.0000,  0.8774,  0.0000,  0.2483,  0.0000,  0.0000,  0.0000,
         0.0685,  0.4387,  2.0268])
data 122
tensor([ 0.0000,  0.8774,  0.0000,  0.2483,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  1.5607])
data 122
tensor([ 0.0000,  0.8774,  0.0000,  0.2483,  0.0000,  0.5350,  0.0000,
         1.2496,  0.0000,  0.0000])
data 122
tensor([ 0.0000,  0.8774,  0.0000,  0.2483,  0.0000,  0.1080,  0.8744,
     

         0.0000,  0.0000,  1.4789])
data 95
tensor([ 0.5350,  0.0000,  1.2496,  0.0000,  0.0000,  1.2244,  0.0000,
         0.0000,  1.8640,  0.0076])
data 95
tensor([ 0.5350,  0.0000,  1.2496,  0.0000,  0.0000,  0.9541,  0.2173,
         0.0000,  0.0000,  0.0000])
data 139
tensor([ 1.2244,  0.0000,  0.0000,  1.8640,  0.0076,  0.1225,  0.0000,
         0.0000,  0.0000,  1.4789])
data 139
tensor([ 1.2244,  0.0000,  0.0000,  1.8640,  0.0076,  0.5350,  0.0000,
         1.2496,  0.0000,  0.0000])
data 139
tensor([ 1.2244,  0.0000,  0.0000,  1.8640,  0.0076,  0.9541,  0.2173,
         0.0000,  0.0000,  0.0000])
data 139
tensor([ 1.2244,  0.0000,  0.0000,  1.8640,  0.0076,  0.8046,  0.7059,
         0.0000,  0.0000,  0.0000])
data 150
tensor([ 0.9541,  0.2173,  0.0000,  0.0000,  0.0000,  0.5350,  0.0000,
         1.2496,  0.0000,  0.0000])
data 150
tensor([ 0.9541,  0.2173,  0.0000,  0.0000,  0.0000,  1.2244,  0.0000,
         0.0000,  1.8640,  0.0076])
data 150
tensor([ 0.9541,  0.2173,  0.

tensor([ 0.6017,  0.5292,  0.6238,  0.7343,  0.8866,  0.0000,  0.0170,
         0.2618,  0.6776,  0.0000])
data 74
tensor([ 0.0000,  0.0000,  0.0000,  1.2138,  1.6951,  0.0582,  0.2748,
         0.1489,  0.0000,  0.0000])
data 74
tensor([ 0.0000,  0.0000,  0.0000,  1.2138,  1.6951,  0.6017,  0.5292,
         0.6238,  0.7343,  0.8866])
data 74
tensor([ 0.0000,  0.0000,  0.0000,  1.2138,  1.6951,  0.0000,  0.0170,
         0.2618,  0.6776,  0.0000])
data 74
tensor([ 0.0000,  0.0000,  0.0000,  1.2138,  1.6951,  0.1152,  0.3436,
         0.0000,  0.0000,  0.0777])
data 156
tensor([ 0.0000,  0.0170,  0.2618,  0.6776,  0.0000,  0.6017,  0.5292,
         0.6238,  0.7343,  0.8866])
data 156
tensor([ 0.0000,  0.0170,  0.2618,  0.6776,  0.0000,  0.0000,  0.0000,
         0.0000,  1.2138,  1.6951])
data 156
tensor([ 0.0000,  0.0170,  0.2618,  0.6776,  0.0000,  0.1152,  0.3436,
         0.0000,  0.0000,  0.0777])
data 156
tensor([ 0.0000,  0.0170,  0.2618,  0.6776,  0.0000,  0.0582,  0.2748,
     

tensor([ 0.0000,  0.0000,  0.0000,  1.4455,  0.0000,  2.0390,  0.0182,
         1.3158,  0.0952,  0.1921])
data 259
tensor([ 0.0000,  0.0000,  0.0000,  1.4455,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  1.3380])
data 259
tensor([ 0.0000,  0.0000,  0.0000,  1.4455,  0.0000,  0.0000,  0.9860,
         0.0000,  0.7566,  0.8767])
data 260
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.3380,  2.0390,  0.0182,
         1.3158,  0.0952,  0.1921])
data 260
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.3380,  0.0000,  0.0000,
         0.0000,  1.4455,  0.0000])
data 260
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.3380,  0.0000,  0.9860,
         0.0000,  0.7566,  0.8767])
data 260
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  1.3380,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  0.0000,  0.0000,
         0.0000,  1.4455,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  0.0000,  0.0000,
 

tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0582,  0.2748,
         0.1489,  0.0000,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.9627,  0.0000,
         1.1066,  0.6987,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0000,  0.0000,
         0.2182,  0.8444,  0.2828])
data 9
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.9627,  0.0000,
         1.1066,  0.6987,  0.0000])
data 9
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 9
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.2182,  0.8444,  0.2828])
data 9
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 10
tensor([ 0.0000,  0.0000,  0.2182,  0.8444,  0.2828,  0.0000,  0.1369,
         0.8353,

         0.3067,  0.0000,  0.0000])
data 67
tensor([ 0.0494,  0.1900,  0.0000,  0.0000,  0.0000,  0.0080,  0.0000,
         0.2101,  0.0000,  0.0000])
data 67
tensor([ 0.0494,  0.1900,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.9689,  1.0342,  1.2235])
data 67
tensor([ 0.0494,  0.1900,  0.0000,  0.0000,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 68
tensor([ 0.0000,  0.0000,  0.9689,  1.0342,  1.2235,  0.0080,  0.0000,
         0.2101,  0.0000,  0.0000])
data 68
tensor([ 0.0000,  0.0000,  0.9689,  1.0342,  1.2235,  0.0494,  0.1900,
         0.0000,  0.0000,  0.0000])
data 68
tensor([ 0.0000,  0.0000,  0.9689,  1.0342,  1.2235,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 68
tensor([ 0.0000,  0.0000,  0.9689,  1.0342,  1.2235,  0.3171,  0.0000,
         0.8472,  0.6028,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.5460,  0.0000,  0.0494,  0.1900,
         0.0000,  0.0000,  0.0000])
data 8
tensor([ 0.0000,  0.1369,  0.8353,  1.

tensor([ 0.0000,  1.5584,  0.0000,  1.0412,  0.5431,  0.0000,  0.0000,
         2.7306,  0.0000,  0.0000])
data 120
tensor([ 0.0000,  1.5970,  0.0000,  1.1138,  0.4729,  0.0000,  0.8128,
         0.0000,  0.2341,  0.0000])
data 120
tensor([ 0.0000,  1.5970,  0.0000,  1.1138,  0.4729,  0.0000,  1.5584,
         0.0000,  1.0412,  0.5431])
data 120
tensor([ 0.0000,  1.5970,  0.0000,  1.1138,  0.4729,  0.0000,  0.0000,
         2.7306,  0.0000,  0.0000])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.0000,  1.5584,
         0.0000,  1.0412,  0.5431])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.0000,  1.5970,
         0.0000,  1.1138,  0.4729])
data 74
tensor([ 0.0000,  0.0000,  0.0000,  1.2138,  1.6951,  1.3339,  0.3691,
         0.2925,  0.0000,  0.0000])
data 74
tensor([ 0.0000,  0.0000,  0.0000,  1.2138,  1.6951,  0.0000,  0.8774,
         0.0000,  0.2483,  0.0000])
data 121
tensor([ 1.3339,  0.3691,  0.2925,  0.0000,  0.0000,  0.0000,  0.0000,
     

tensor([ 1.5312,  0.8795,  2.1102,  1.9857,  0.0000,  0.3635,  0.0000,
         1.5981,  0.0000,  0.0000])
data 18
tensor([ 1.5312,  0.8795,  2.1102,  1.9857,  0.0000,  0.0000,  0.9860,
         0.0000,  0.7566,  0.8767])
data 167
tensor([ 0.3635,  0.0000,  1.5981,  0.0000,  0.0000,  0.0000,  1.3625,
         0.5639,  0.8215,  0.0000])
data 167
tensor([ 0.3635,  0.0000,  1.5981,  0.0000,  0.0000,  1.5312,  0.8795,
         2.1102,  1.9857,  0.0000])
data 167
tensor([ 0.3635,  0.0000,  1.5981,  0.0000,  0.0000,  0.0000,  0.9860,
         0.0000,  0.7566,  0.8767])
data 167
tensor([ 0.3635,  0.0000,  1.5981,  0.0000,  0.0000,  0.0000,  1.8276,
         0.0000,  0.6419,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  1.5312,  0.8795,
         2.1102,  1.9857,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  0.3635,  0.0000,
         1.5981,  0.0000,  0.0000])
data 168
tensor([ 0.0000,  0.9860,  0.0000,  0.7566,  0.8767,  0.0000,  1.8276,
  

tensor([ 0.0000,  0.0000,  0.0374,  0.1778,  1.3081,  0.6017,  0.5292,
         0.6238,  0.7343,  0.8866])
data 207
tensor([ 0.0000,  0.0000,  0.0374,  0.1778,  1.3081,  0.0000,  0.0000,
         2.7306,  0.0000,  0.0000])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.6017,  0.5292,
         0.6238,  0.7343,  0.8866])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0374,  0.1778,  1.3081])
data 208
tensor([ 0.0000,  1.0955,  0.0000,  0.0893,  0.0000,  0.0000,  0.0000,
         0.0000,  0.4723,  0.0000])
data 208
tensor([ 0.0000,  1.0955,  0.0000,  0.0893,  0.0000,  0.3148,  0.0000,
         1.6240,  0.6385,  1.1458])
data 46
tensor([ 0.0000,  0.0000,  0.0000,  0.4723,  0.0000,  0.0000,  1.0955,
         0.0000,  0.0893,  0.0000])
data 46
tensor([ 0.0000,  0.0000,  0.0000,  0.4723,  0.0000,  0.3148,  0.0000,
         1.6240,  0.6385,  1.1458])
data 46
tensor([ 0.0000,  0.0000,  0.0000,  0.4723,  0.0000,  0.0000,  0.5715,
      

data 231
tensor([ 1.3172,  0.0000,  0.2850,  1.4147,  0.0000,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 231
tensor([ 1.3172,  0.0000,  0.2850,  1.4147,  0.0000,  0.0000,  0.5477,
         0.0000,  1.0770,  0.0000])
data 231
tensor([ 1.3172,  0.0000,  0.2850,  1.4147,  0.0000,  0.1080,  0.8744,
         0.0000,  0.2145,  0.0000])
data 231
tensor([ 1.3172,  0.0000,  0.2850,  1.4147,  0.0000,  0.3162,  1.3044,
         0.0000,  1.4172,  0.0000])
data 36
tensor([ 0.1080,  0.8744,  0.0000,  0.2145,  0.0000,  0.0000,  0.5477,
         0.0000,  1.0770,  0.0000])
data 36
tensor([ 0.1080,  0.8744,  0.0000,  0.2145,  0.0000,  1.3172,  0.0000,
         0.2850,  1.4147,  0.0000])
data 36
tensor([ 0.1080,  0.8744,  0.0000,  0.2145,  0.0000,  0.3162,  1.3044,
         0.0000,  1.4172,  0.0000])
data 36
tensor([ 0.1080,  0.8744,  0.0000,  0.2145,  0.0000,  0.0000,  0.0000,
         1.1793,  0.0000,  0.0000])
data 232
tensor([ 0.3162,  1.3044,  0.0000,  1.4172,  0.0000,  1.3172,  0.00

tensor([ 0.4185,  0.2911,  1.2268,  0.0518,  0.0000,  0.8327,  0.0000,
         0.0397,  0.5506,  1.0354])
data 272
tensor([ 0.4185,  0.2911,  1.2268,  0.0518,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 272
tensor([ 0.4185,  0.2911,  1.2268,  0.0518,  0.0000,  0.0000,  0.0000,
         2.7306,  0.0000,  0.0000])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.0000,  0.1369,
         0.8353,  1.5460,  0.0000])
data 23
tensor([ 0.0000,  0.0000,  2.7306,  0.0000,  0.0000,  0.4185,  0.2911,
         1.2268,  0.0518,  0.0000])
data 28
tensor([ 1.4322,  1.1425,  0.0000,  0.0000,  0.0000,  0.3596,  2.2117,
         0.0000,  0.8276,  0.0000])
data 28
tensor([ 1.4322,  1.1425,  0.0000,  0.0000,  0.0000,  0.1080,  0.8744,
         0.0000,  0.2145,  0.0000])
data 192
tensor([ 0.3596,  2.2117,  0.0000,  0.8276,  0.0000,  1.4322,  1.1425,
         0.0000,  0.0000,  0.0000])
data 192
tensor([ 0.3596,  2.2117,  0.0000,  0.8276,  0.0000,  0.1080,  0.8744,
     

data 301
tensor([ 0.3734,  2.0300,  0.0000,  0.0000,  0.0000,  0.2971,  0.6734,
         0.1401,  0.0000,  0.0000])
data 301
tensor([ 0.3734,  2.0300,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000])
data 301
tensor([ 0.3734,  2.0300,  0.0000,  0.0000,  0.0000,  0.8327,  0.0000,
         0.0397,  0.5506,  1.0354])
data 302
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.2971,  0.6734,
         0.1401,  0.0000,  0.0000])
data 302
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.3734,  2.0300,
         0.0000,  0.0000,  0.0000])
data 302
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.8327,  0.0000,
         0.0397,  0.5506,  1.0354])
data 302
tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.1495,  0.1095,
         1.0434,  0.1118,  0.0753])
data 34
tensor([ 0.8327,  0.0000,  0.0397,  0.5506,  1.0354,  0.3734,  2.0300,
         0.0000,  0.0000,  0.0000])
data 34
tensor([ 0.8327,  0.0000,  0.0397,  0.5506,  1.0354,  0.0000,  0.

In [31]:
z_t.size()

torch.Size([5])

In [47]:
z(10)

TypeError: 'Tensor' object is not callable